spring.application.name=Application
spring.datasource.url=jdbc:mySql://localhost:3306/appdb
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
server.port=9102